modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile = "assets/storageboxadapter/icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "pitan76"
description = '''
StorageBox mod addon that able to import to/export from StorageBox
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mcpitanlib"
mandatory = true
versionRange = "[3.0.0,)"
ordering = "BEFORE"
side = "BOTH"

